apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: edgexes.vmware.com
spec:
  group: vmware.com
  names:
    kind: EdgeX
    listKind: EdgeXList
    plural: edgexes
    singular: edgex
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
